### ISSUE TITLE
Character gets stuck/pushed

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1134]
sometimes the characters will get stuck moving in one direction you have to spam that direction its stuck in for it to stop or relog, also entitys push the character around so I was told in discord to remove this code from the character controller  entity movement it didnt help with the stuck in one direction sometimes helped a little with monsters pushing any advice?
```
platformMotion = Vector3.zero;
            if (isGrounded && !isUnderWater)
            {
                // Apply platform motion
                if (groundedTransform != null && deltaTime > 0.0f)
                {
                    Vector3 newGroundedPosition = groundedTransform.TransformPoint(groundedLocalPosition);
                    platformMotion = (newGroundedPosition - oldGroundedPosition) / deltaTime;
                    oldGroundedPosition = newGroundedPosition;
                }
            }
```

**Comment by insthync** [comment]
I don't get how it is, can you capture the video?

**Comment by moepi2k** [comment]
I think the first thing he means is when u press for example A it could happen when u release button the character still walk left, W S D will not work then and u need to spam A to stop the player. I also have this problem sometimes, happens mlst then when öress other buttons while walking like opening gui or something.

Second with platform motion is that enemies also could count as platorm and then they push you with. Best way would be to ignore character layer for platform motion

**Comment by Sour-J** [comment]
I'll get back to you on this with a video it's random

**Comment by Sour-J** [comment]
Here's the video submitted by one of my players he said to reproduce, all you gotta do is drop an item, press F to pick it up and you're stuck it also happen randomly while attacking 

https://user-images.githubusercontent.com/78616165/133302052-040c720a-7894-489d-a0ac-f94edb5f17a6.mp4

**Comment by Sour-J** [comment]
I also found a way to reproduce, if you set the attack animation faster so the character attacks fast and you walk left with A and spam the left click single fire attack it makes the character stuck walking left if you let go

**Comment by insthync** [comment]
Which player character controller?, `Shooter Player Character Controller`?

**Comment by Sour-J** [comment]
> Which player character controller?, `Shooter Player Character Controller`?

Yes the shooter controller 
I am also using CC navmesh agent

**Comment by moepi2k** [comment]
actually it happens with all. i use aimatcursors for example and have same issue

**Comment by LordPhrozen** [comment]
Rapidly tapping A,D,A,D,A,D,A,D,A,D,A,D,A,D,A,D,A,D will get you this. From what I can tell, it throws the character into an "unanimated frame", as it attempts to swap between the states.

**Comment by moepi2k** [comment]
@LordPhrozen this issue is fixxed in 1.69c.thus post explains another bug

**Comment by LordPhrozen** [comment]
> @LordPhrozen this issue is fixxed in 1.69c.thus post explains another bug

Definitely misread. in the process of updating now.

**Comment by Sour-J** [comment]
I still have the same issue with the new version and i even switched to playable character controller

**Comment by insthync** [comment]
@Sour-J  I didn't fix it yet, If I fix it I will tell you here.

**Comment by insthync** [comment]
In 1.69d 
I've added `Platform Layer Mask` setting to `Rigidbody Entity Movement` and `Character Controller Entity Movement`, set layers of objects that you want to be platform here.

But I actually cannot reproduce the character keep moving to 1 direction issues yet.

**Comment by moepi2k** [comment]
as i understand correctly sourj mention two diffrent problems. 
1) is the platform motion issue where enemies or other players push you when platformmotions becomes active.

2) is that player walk in one direction without pressing any button. this issue happens sometime when u walk and at same time u open inventory or interacting the ui. then it can happen that the player moves in one direction when you release the buttons.
for example when the player then walks left you cant walk forward backwards or right. you need to push that button in what direction the players move to stop him. its an issue that happen sometimes in older games also.

maybe a simple fix would be to check if button is released, i dont know.

its hard to make a video for that because you cant see what buttons are pressed. but it happen to me many times.

**Comment by Sour-J** [comment]
> as i understand correctly sourj mention two diffrent problems.
> 
> 1. is the platform motion issue where enemies or other players push you when platformmotions becomes active.
> 2. is that player walk in one direction without pressing any button. this issue happens sometime when u walk and at same time u open inventory or interacting the ui. then it can happen that the player moves in one direction when you release the buttons.
>    for example when the player then walks left you cant walk forward backwards or right. you need to push that button in what direction the players move to stop him. its an issue that happen sometimes in older games also.
> 
> maybe a simple fix would be to check if button is released, i dont know.
> 
> its hard to make a video for that because you cant see what buttons are pressed. but it happen to me many times.

Exactly I thought the two issues were related to the platform code but I'll update and see if fixed and report back it is hard to record these issues like you mentioned

**Comment by moepi2k** [comment]
the second one has nothing to do with platform motion. it seems that key pressed stucking sometimes while doing multible actions. it also could be that when u walk with W A S D sometimes it interact a button in the UI like chat or other things like the Mail, Crafting and so on.

**Comment by Sour-J** [comment]
So far i cant reproduce this on the new update 1.69d so i think its fixed, I am about to have another closed beta test with the public again this week and ill report back, my players were the ones to find this out these issues in the first place.

 I know you say their not related but when i turn the platform layer mask to ''nothing'' on character controller entity movement it seems to resolve one of the issues and i didnt comment out the platform motion code. Maybe the update fixed the other issue that @moepi2k said was not related to platform motion on another script in the update. So in general both seem to be resolved with 1.69d.

ill let you know what the players say about it with the new update im going to put on steam this week.  

thank you for fixing this @insthync  I appreciate you

**Comment by moepi2k** [comment]
I dont think that the second one is fixed, it has nothing todo with platform motion. I will test it also on 1.69d

**Comment by Sour-J** [comment]
> I dont think that the second one is fixed, it has nothing todo with platform motion. I will test it also on 1.69d

Your right the second issue is still happening

**Comment by Sour-J** [comment]
I am still experiencing this issue :( i tried to remove the platform movement but i still get pushed in one direction while attacking its not stuck on the monster its just stuck moving that direction this issue that was said above by @moepi2k :

is that player walk in one direction without pressing any button. this issue happens sometime when u walk and at same time u open inventory or interacting the ui. then it can happen that the player moves in one direction when you release the buttons.
for example when the player then walks left you cant walk forward backwards or right. you need to push that button in what direction the players move to stop him. its an issue that happen sometimes in older games also.

**Comment by insthync** [comment]
How can I reproduce it?

It's the same problem with pressing `Enter` button to enter chat while moving? If yes, the source of the problem might be InputField focus state detection.

**Comment by Sour-J** [comment]
Not sure how to reproduce but I'm happy to give you a copy of the game so you can see. The best way I can explain is. When your using the shooter controller, tap left click fast or V spam the attacks on a monster while also pressing a and d rapidly the character will get stuck moving forward or to the side and you have to press the key in the direction its moving in to stop it.

**Comment by Sour-J** [comment]
> Rapidly tapping A,D,A,D,A,D,A,D,A,D,A,D,A,D,A,D,A,D will get you this. From what I can tell, it throws the character into an "unanimated frame", as it attempts to swap between the states, which tries to shove the character model downward.

this is a good way of explaining it too

**Comment by LordPhrozen** [comment]
We just conducted our first PVP test, and we saw a few players that mentioned getting "stuck moving" as if the key was held down, but wasn't.

These players were ones that were rapidly using the WASD keys.

This is under 1.70f

**Comment by moepi2k** [comment]
> How can I reproduce it?
> 
> It's the same problem with pressing `Enter` button to enter chat while moving? If yes, the source of the problem might be InputField focus state detection.

i have it many times when enter chat, yes. so while walk ent press enter, player auto walks.

but sometimes i have the issue when walk and interacting with ui.

**Comment by Sour-J** [comment]
Mine is not UI related at all just spamming like.lord phrozen said. Rapidly tapping A,D,A,D,A,D,A,D,A,D,A,D,A,D,A,D,A,D will get you this. From what I can tell, it throws the character into an "unanimated frame", as it attempts to swap between the states, which tries to shove the character model downward.

So attack a monster using shooter controller spam a d ad ad ad ad and also spam click to attack while pressing a and d rapidly 

I haven't tried to see if it's fixed in the newest update but will let you know and post a video of it

**Comment by insthync** [comment]
An unanimated frame was fixed around a month ago.

**Comment by moepi2k** [comment]
We discuse this issue atm in doscord, we all still have the issue, that player auto walks in one direction

**Comment by insthync** [comment]
Now it is pretty confusing because we are talking about 2 different issues in same thread.
The only problem which doesn't fix is auto walks in one direction, right?

**Comment by moepi2k** [comment]
Exctly

**Comment by insthync** [comment]
Try 1.71d, if it is not fixed, can reopen this.

**Comment by Sour-J** [comment]
confirm fixed in 1.71d both issues

**Comment by Sour-J** [comment]
confirm fixed in 1.71d both issues
