### ISSUE TITLE
The player can still attack on the old weapon after switching to the new weapon

### ISSUE THREAD

**Issue by langtusaupt** [suriyun-production/mmorpg-kit-docs#1255]
When player play animation attack, use hotkey to switch new weapon, The player still play animation attack on the old weapon

**Comment by insthync** [comment]
I will prevent the character to switch weapons while playing attack animation in next version.

**Comment by insthync** [comment]
Fixed in 1.71b

**Comment by langtusaupt** [comment]
You have fixed the error when switching weapons, but the error still occurs when you unequip the current weapon when play skill or attack animation

**Comment by insthync** [comment]
Fixed, it will be included in next version.
