### ISSUE TITLE
[Bug]Animation Speed for PlayableCharacterModel not working

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1261]
https://gyazo.com/2d827932f4ed061e7fad0618b0bbfae1

you can change value but animation speed is always same

**Comment by insthync** [comment]
Fixed in 1.71b

**Comment by moepi2k** [comment]
this still not working. i set speed to 5 but nothing changes
