### ISSUE TITLE
character position

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1708]
Hello, I have this error when I am in MMO

The truth is that it happens to me often but it is not something that I can reproduce exactly, only sometimes the position of the character is not updated correctly.

https://imgur.com/a/hwsPuCk

**Comment by insthync** [comment]
Fixed in 1.77d2

**Comment by Blunnyn** [comment]
I still have the same error
https://imgur.com/a/l7IxsLt
https://imgur.com/a/LxtMsZc

**Comment by Blunnyn** [comment]
Actually this happens randomly. I use the mount to return to the "stowed" position.

**Comment by insthync** [comment]
Try fix it by changes codes in entity movement `ReadServerStateAtClient` function 
find 
```
if (acceptedPositionTimestamp < timestamp)
```
change it to 
```
if (acceptedPositionTimestamp <= timestamp)
```

**Comment by Blunnyn** [comment]
It doesn't work. Indeed, the problem arises when you are on the mount and then you get off it.

**Comment by insthync** [comment]
But as I try it work

**Comment by insthync** [comment]
Zip me your game, then I will test it.

**Comment by Blunnyn** [comment]
Done, send it to your email
