### ISSUE TITLE
Animation of Melee Off-Hand Remains when changing to Bow (Two Hand)

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1961]
So, I have this problem. I am using dual dagger with 3 animations of Right Hand and 3 on left Hand.
![image](https://user-images.githubusercontent.com/118698151/227554908-fff1a9a7-0543-4908-89b3-08244242da66.png)
![image](https://user-images.githubusercontent.com/118698151/227554965-d28233f2-2b2d-4cc0-88cd-da3026f3ffc2.png)

When I change to BOW (Two Hand Wield), the animation of dual dagger remains, its the 2nd animation of the dagger that remains. And here is my bow animation.

![image](https://user-images.githubusercontent.com/118698151/227555330-2456a4ac-fac8-4161-b091-15bcb1f3929b.png)

This is the video demo of the problem.

https://user-images.githubusercontent.com/118698151/227555565-47871d98-1ce9-4fb0-86e7-5b6516c14d9b.mp4

I also tried using Right Hand on the dagger only but the problem is the same. I also tried adding the right hand animation of the bow to left hand, same result.

**Comment by insthync** [comment]
Which version?, I remember that it is already fixed

**Comment by AsheshPlays** [comment]
@insthync
All good now! Thanks!

**Comment by AsheshPlays** [comment]
I am updated to 1.81f2 and it seems the issue is back again.. I thought it was ok last night because nothing happened. Now it seems the problem is still occuring.

![image](https://user-images.githubusercontent.com/118698151/227712416-5d306eb4-5064-4596-9e3d-1a629a3e98a1.png)

Here is the video of the problem.
https://user-images.githubusercontent.com/118698151/227712513-f8e37d4b-13b9-4810-b639-dcf382703f21.mp4

**Comment by insthync** [comment]
I think I have to try yours by using AnyDesk, I will charge you 30 USD if the problem is just like wrong source codes importing, if not I will fix it for free, are you ok?

**Comment by insthync** [comment]
Okay, I can reproduce it

**Comment by insthync** [comment]
Fixed in 1.81g

**Comment by AsheshPlays** [comment]
@insthync Thank you! Will test it right away.
