### ISSUE TITLE
[Bug] Party not working as expected

### ISSUE THREAD

**Issue by vgabler** [suriyun-production/mmorpg-kit-docs#2022]
Party still has many different bugs, using version 1.82c3
Attaching a video to show the problems. But here's the summary:
- members won't appear on the list
- exp / item share will give only the non-leader exp or gold
- if you leave the party as the leader, the party is disbanded but the leader get stuck in it

https://user-images.githubusercontent.com/24776058/232619188-6ea7e86b-5b06-4fe6-a98f-ff2651b70f4e.mp4

I'm using a fresh install, Unity version 2020.3.26f1.

I had to change this line from BaseCharacterModel.cs, probably because the "includeInactive" parameter exists only in newer versions
![image](https://user-images.githubusercontent.com/24776058/232619953-526ad867-ec65-4259-a7a6-b38a7bbd0819.png)

**Comment by insthync** [comment]
Yep, it was reported, I've fixed it, and never occurred when I test it, about the Unity version, why just don't use 2020.3.46f1?

**Comment by moepi2k** [comment]
jup still same problem still at 182c3
using unity 2021.3.16. party broken and player not listed in it correctly. also leaving party not work

**Comment by insthync** [comment]
Maybe because you not report all whats you've done

**Comment by insthync** [comment]
Such as that party was just created or created before you login

**Comment by insthync** [comment]
You guys didn't tell me how to reproduce

**Comment by moepi2k** [comment]
fresh project, fresh db, just login in create party. nothing changed.

https://gyazo.com/20efbdc0b2d862b1168061a99c0318b3

**Comment by insthync** [comment]
Try UnityMultiplayerARPG_1.82c4

**Comment by moepi2k** [comment]
that works

**Comment by vgabler** [comment]
@insthync sorry for not giving more details on how to reproduce!
I said only it was on fresh install.

Just tested v 1.82c4, seems like it's fixed. Thank you very much!
