### ISSUE TITLE
Damageable Hitbox

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2037]
Hello,

I've tried to use the Damageable hitbox on my charactrer and monsters. I just found out that when the attack is AOE (An explosion) like a grenade, it will hit every single damageable hitbox instead of one. So for example if the character have 7 damageable hitbox on him. and a grenade explode on him. The grenade damage will trigger 7 times instead of 1. So Instead of 20 damage, it will be 20+20+20+20+20....

I dont know if it would be possible to fix that, to only accept 1 damage received from the same attack. 

The damageable hitbox still need to be able to be attacked from multiple targets at once, so i dont know how we could do it.

**Comment by insthync** [comment]
I actually added hit objects checking, you can see it in `ThrowableDamageEntity` component (find: `alreadyHitObjects`) if it is not working then I will fix it.

I don't stand this "The damageable hitbox still need to be able to be attacked from multiple targets at once, so i dont know how we could do it.", so it need to be attacked from multiple targets or not?

**Comment by insthync** [comment]
As I try Throwable Damage Entity, it is works properly.

**Comment by Eniotnacram** [comment]
I am using the missile damage entity, with an explosion setup on it. When my fireball (using the missile damage entity) hits the enemy (with multiples damageable hitbox). Instead of doing a single damage for example 70 damage. it will do 70 damage on every dameable hitbox it hits. So if my damage explosion radius is like 5. It will hit all of the damageable hitbox and do 70+70+70+70 etc...

**Comment by insthync** [comment]
So it is missile damage entiy, not a throwable damage entity, right?

**Comment by Eniotnacram** [comment]
Yea missile damage entity. With an explosion setup on it.

**Comment by Eniotnacram** [comment]
![Screenshot 2023-04-24 123142](https://user-images.githubusercontent.com/46734935/234059492-b7e66034-c753-422b-ab91-42f1e3f5bcb9.png)

**Comment by Eniotnacram** [comment]
Because of the explode Distance, if it explode touching more than 1 damageable hitboxs, it will do damage on all damageable hitbox touched by the explosion (on the same character/monster) Also, I dont know if its because of the explosion setup, but kinda often, the damage just doesnt register on hit. My shot directly hit an enemy and sometimes it just do nothing. Maybe it is a sync problem with the server

**Comment by Eniotnacram** [comment]
Look I made a video for you. The second hit the 6 and the 7 didint do damage. But clearly hits the target:
https://medal.tv/games/requested/clips/16h61tPO3veuhr/d1337JgD0XHs?invite=cr-MSxjUmssNDQ3NDMxODYs

**Comment by insthync** [comment]
Fixed in 1.82d

**Comment by Eniotnacram** [comment]
Im still having issue with multiple damageable hitboxs There is a video: https://medal.tv/games/requested/clips/16tQXdhcx8yJ02/d13370WLQCsh?invite=cr-MSxtTmYsNDQ3NDMxODYs

My Goblin have 2 damageable hitbox on it. One for the head and one for the body. Head 1.2X damage. But when attacking him, as my missile have an explosion, it hits both damageable hitbox at the same time and do double damage.
