### ISSUE TITLE
Quest Bug (Or not) Complete After Talked.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2089]
Hello,

For the task "Talk To Npc" when "complete after talked" is checked, the quest task shows (Completed) before talking to the Npc.

I dont know if its a bug or not, but it is not really good either way. For exemple, the player receive that brand new quest, and in the task, its saying: "Talk to Santa (Completed)"... Player will wonder why the quest is already completed if he didin't talk to the npc yet.

Ive fixed that by removing the (Completed) in the language manager. But it would be fun if this can be fixed because now i simply cannot use (Completed) text for my other quests.

Thank you.

**Comment by moepi2k** [comment]
Noticed same

**Comment by insthync** [comment]
Fixed in 1.83e

**Comment by Eniotnacram** [comment]
Not fixed for me in Version 1.83e. Still see complete before talking to the Npc. @insthync

**Comment by Eniotnacram** [comment]
Video: https://medal.tv/games/requested/clips/1arKhfSKAZ5AAR/d1337yNZGkmI?invite=cr-MSxBVUMsNDQ3NDMxODYs

**Comment by insthync** [comment]
https://youtu.be/wSMZwx40_BY Is this is what you want?

**Comment by Eniotnacram** [comment]
Yes! That it shows "ongoing" if player didn't talk to npc. And not only the Title of the quest, but the task too.

Ex:
-Where is Santa Claus (Ongoing) "TITLE"
-Talk to Santa Claus. "TASK"

**Comment by insthync** [comment]
Yep, I did it in 1.83e

**Comment by Eniotnacram** [comment]
You did this also for the toggled quests? In the party/quest UI? Because I tried it this morning and didn't worked for me. I didn't check in the UI Quests Dialog tho.

**Comment by insthync** [comment]
![Screenshot_679](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/30c50e67-d0af-4719-ade4-9ec4aa6e17bc)

This?

**Comment by Eniotnacram** [comment]
Brand new project, brand new imported kit, 1.83e. The title of the quest is right, but the task has not been modified. Still shows Complete before talking to NPC.

![Screenshot 2023-05-22 144712](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46734935/53f8c45d-4abe-4da6-952c-e84e7e36470b)

**Comment by insthync** [comment]
Try e2

**Comment by Eniotnacram** [comment]
> Try e2

where can i try it? I always download new versions from the package manager I dont have git repo access

**Comment by insthync** [comment]
Yep, then try it from Unity

**Comment by Eniotnacram** [comment]
> Yep, then try it from Unity

it is not released for me yet on the package manager

**Comment by insthync** [comment]
Then you have to wait

**Comment by Eniotnacram** [comment]
Working! Thank you @insthync
