### ISSUE TITLE
Multiple problem with mount [Critical 1.55c ver]

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#441]
- In multiplayer only the hoster can moving with a mount, the other player can just ride but not move
- When a mount have multiple sit, when the owner rider quit the mount, the other player was sit too stay in air and have to disconnect and reconnect to the game
- When the rider strafe left or right with the mount the change place and go down to the seat point 

Confirm if you have those problem too please

**Comment by insthync** [comment]
I will check it. Thank for bugs report :)

**Comment by dglee2592** [comment]
> I will check it. Thank for bugs report :)

Can you also check when mount in the water? 
Third issue(seat position down) happens when go into water

**Comment by Gui205** [comment]
> > I will check it. Thank for bugs report :)
> 
> Can you also check when mount in the water?
> Third issue(seat position down) happens when go into water

I got this issue also on ground

**Comment by insthync** [comment]
About
```
When the rider strafe left or right with the mount the change place and go down to the seat point
```
Try set empty movement clips
![Screenshot_178](https://user-images.githubusercontent.com/2697550/83076377-a06d8e00-a09f-11ea-9c65-77dc1b2b7f0a.png)

Next version I will make it assigning default move clip if it's empty.

**Comment by Gui205** [comment]
> About
> 
> ```
> When the rider strafe left or right with the mount the change place and go down to the seat point
> ```
> 
> Try set empty movement clips
> ![Screenshot_178](https://user-images.githubusercontent.com/2697550/83076377-a06d8e00-a09f-11ea-9c65-77dc1b2b7f0a.png)
> 
> Next version I will make it assigning default move clip if it's empty.

I take a look about this problem when is underwater, i have an issue when i chek only swim on the surface, the character or/and the mount have really huge bouncy.

**Comment by insthync** [comment]
How about animation?

**Comment by Gui205** [comment]
> How about animation?, Is it still float underground?

Nop for all animation work good, for the mount and the character with your solution no any problem. Actually just the bouncy issue, and the multiplayer only hoster riding problem

**Comment by insthync** [comment]
Other problems was fixed, I will upload the updated package later.

**Comment by insthync** [comment]
Fixed in 1.55d

**Comment by Gui205** [comment]
Still have the buoyancy issue when i have auto swim to the surface the buoyancy is to huge. And i notice the character "auto slide" also if you have 1° slope since the 1.55d

**Comment by Gui205** [comment]
> Fixed in 1.55d

Have an issue, when hoster use the passager seat he can control the orientation of the mount i made a video for show you the problem, the hoster is the left screen : 
https://youtu.be/IF3oc817lQE

**Comment by insthync** [comment]
O_O!!, I will fix it.

**Comment by Gui205** [comment]
> O_O!!, I will fix it.
This is the buoyancy issue when you allow only the surface swim :
https://youtu.be/TyxKrpCggt8

**Comment by insthync** [comment]
Fixed in 1.56
